name: example
description: "Example App for a flexible Kline package project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flexi_kline:
    path: ../
  flutter_screenutil: ^5.9.0
  decimal: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
