name: example
description: "Example App for a flexible Kline package project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.6

  flexi_kline:
    path: ../

  decimal: ^2.3.3
  go_router: ^14.1.4
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  talker_dio_logger: ^4.2.4
  logger: ^2.3.0
  web_socket_channel: ^2.4.5
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

  flutter_screenutil: ^5.9.3
  flutter_smart_dialog: ^4.9.7+7
  easy_refresh: ^3.4.0
  cached_network_image: ^3.3.1

  flutter_ume_plus: ^3.0.2
  flutter_ume_kit_dio_plus: ^3.4.5
  flutter_ume_kit_perf_plus: ^2.0.1
  flutter_ume_kit_ui_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/imgs/

flutter_intl:
  enabled: true
