name: example
description: "Example App for a flexible Kline package project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.7

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

  flexi_kline:
    path: ../

  decimal: ^2.3.3
  go_router: ^14.3.0
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  dio: ^5.7.0
  talker_dio_logger: ^4.4.1
  logger: ^2.4.0
  web_socket_channel: ^3.0.1
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  device_preview: ^1.1.0
  flutter_screenutil: ^5.9.3
  flutter_smart_dialog: ^4.9.8+3
  easy_refresh: ^3.4.0
  cached_network_image: ^3.4.1
  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.10+1

  flutter_ume_plus: ^4.1.0
  flutter_ume_kit_dio_plus: ^4.1.0
  flutter_ume_kit_perf_plus: ^4.1.0
  flutter_ume_kit_ui_plus: ^4.1.0

dependency_overrides:
  vm_service: ^14.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/imgs/
    - assets/svgs/

flutter_intl:
  enabled: true
