name: flexi_kline
description: "A flexible Kline framework package project."
version: 2.0.0
homepage: https://flexikline.github.io
repository: https://github.com/FlexiKline/FlexiKline
issue_tracker: https://github.com/FlexiKline/FlexiKline/issues
documentation: https://pub.dev/documentation/flexi_kline/latest
topics:
  - chart
  - kline
  - candlestick
  - stock

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.2.4
  flexi_formatter: ^2.0.1
  equatable: ^2.0.8
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  copy_with_extension_gen: ^6.0.1
