name: Flutter Web
on:
  push:
    # branches:
    #  - main
    # Sequence of patterns matched against refs/tags
    tags:
      - "r*"
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.4
          # flutter-version-file: pubspec.yaml # path to pubspec.yaml

      - run: flutter --version

      # 按照下面的顺序执行打包命令
      - run: |
          cd example
          flutter config --enable-web
          # flutter channel master
          flutter pub get
          flutter build web --release

      - run: |
          cd example/build/web
          git init
          # 改成你的提交邮箱
          git config --global user.email kangqiao610@gmail.com
          # 改成你的提交用户名
          git config --global user.name Andy.Zhao
          git status
          # 更改此远程URL，例如查看您的远程URL是 https://github.com/FlexiKline/FlexiKline.git 然后改成以下内容
          git remote add origin https://${{secrets.commit_secret}}@github.com/FlexiKline/FlexiKline.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
